### ISSUE TITLE
Shared weights

### ISSUE THREAD

**Issue by JGuillaumin** [cgyulay/kaggle-digit-recognizer#1]
Hello, 

I'm studying Deep Learning at my own pace, on my free time. 
Your code is very helpful. 

But I don't understand one point .. Why the layers h2 and h3 share the same weights ? 

```
h2 = ConnectedLayer(
      input=h1.output,
      input_dropout=h1.output_dropout,
      n_in=n_hidden,
      n_out=n_hidden,
      rng=rng,
      activation=relu,
      p_dropout=p_dropout_hidden,
      w=w_b[1][0],
      b=w_b[1][1]
    )

    h3 = ConnectedLayer(
      input=h2.output,
      input_dropout=h2.output_dropout,
      n_in=n_hidden,
      n_out=n_hidden,
      rng=rng,
      activation=relu,
      p_dropout=p_dropout_hidden,
      w=w_b[1][0],
      b=w_b[1][1]
    )
```

Thank you in advance for your answer !

**Comment by cgyulay** [comment]
Thanks for the message! As it turns out, my code was definitely incorrect and I've just pushed the fix. Good catch, and good luck on studying deep learning. Glad this repo could help, let me know if you have any more questions.
